name: integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "7.4"
            drupal-version: "~8.9"
          - php-version: "7.4"
            drupal-version: "^9"
          - php-version: "8.0"
            drupal-version: "^9"
          - php-version: "8.1"
            drupal-version: "^10"
          - php-version: "8.2"
            drupal-version: "11.x-dev"
    env:
      extensions: zip, gd
      key: cache-v1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@develop
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          tools: composer:v2

      # Execute out script directly without `uses`
      # core.getInput() checks for environment variablts prefixed INPUT_*
      # process.env[`INPUT_${name.replace(/ /g, '_').toUpperCase()}`] || ''
      - name: Setup Drupal
        run: node dist/index.js
        env:
          INPUT_VERSION: ${{ matrix.drupal-version }}
          INPUT_PATH: ~/drupal
          INPUT_ALLOW_PLUGINS: oomphinc/composer-installers-extender
      - name: Debug composer.json
        run: cat ~/drupal/composer.json
      - name: Include plugin
        run: cd ~/drupal && composer require oomphinc/composer-installers-extender
      - name: Verify build
        run: test -f ~/drupal/web/index.php
